[2024-04-22T04:30:31.942+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T04:30:29.456282+00:00 [queued]>
[2024-04-22T04:30:31.979+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T04:30:29.456282+00:00 [queued]>
[2024-04-22T04:30:31.983+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-22T04:30:32.033+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_Data_Submission_Reddit> on 2024-04-22 04:30:29.456282+00:00
[2024-04-22T04:30:32.045+0000] {standard_task_runner.py:60} INFO - Started process 865 to run task
[2024-04-22T04:30:32.104+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'get_Data_Submission_Reddit', 'manual__2024-04-22T04:30:29.456282+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmpdlsc7t_9']
[2024-04-22T04:30:32.114+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask get_Data_Submission_Reddit
[2024-04-22T04:30:32.248+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T04:30:29.456282+00:00 [running]> on host d4c97f52cb78
[2024-04-22T04:30:32.667+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='get_Data_Submission_Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T04:30:29.456282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T04:30:29.456282+00:00'
[2024-04-22T04:30:33.009+0000] {logging_mixin.py:188} INFO - True
[2024-04-22T04:30:34.737+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T04:30:34.751+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 46, in _get_Data_Submission_Reddit
    json.dump(data, f)
NameError: name 'data' is not defined
[2024-04-22T04:30:34.771+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=get_Data_Submission_Reddit, execution_date=20240422T043029, start_date=20240422T043031, end_date=20240422T043034
[2024-04-22T04:30:34.984+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task get_Data_Submission_Reddit (name 'data' is not defined; 865)
[2024-04-22T04:30:35.059+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T04:30:35.236+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
