[2024-04-22T09:09:16.059+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [queued]>
[2024-04-22T09:09:16.085+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [queued]>
[2024-04-22T09:09:16.086+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-22T09:09:16.148+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_Data_CommentSubmission_Reddit> on 2024-04-22 09:09:12.275139+00:00
[2024-04-22T09:09:16.159+0000] {standard_task_runner.py:60} INFO - Started process 18116 to run task
[2024-04-22T09:09:16.173+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_CommentSubmission_Reddit_pipeline', 'get_Data_CommentSubmission_Reddit', 'manual__2024-04-22T09:09:12.275139+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/GetComment.py', '--cfg-path', '/tmp/tmp4i6qaakn']
[2024-04-22T09:09:16.176+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask get_Data_CommentSubmission_Reddit
[2024-04-22T09:09:16.326+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [running]> on host d4c97f52cb78
[2024-04-22T09:09:16.916+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_CommentSubmission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='get_Data_CommentSubmission_Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T09:09:12.275139+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T09:09:12.275139+00:00'
[2024-04-22T09:09:16.982+0000] {logging_mixin.py:188} INFO - True
[2024-04-22T09:09:18.472+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetComment.py", line 35, in _get_Data_CommentSubmission_Reddit
    for comment in reddit.comment("dataengineering").new(limit=20):
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/base.py", line 35, in __getattr__
    self._fetch()
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/comment.py", line 192, in _fetch
    raise ClientException(f"No data returned for comment {self.fullname}")
praw.exceptions.ClientException: No data returned for comment t1_dataengineering
[2024-04-22T09:09:18.485+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_CommentSubmission_Reddit_pipeline, task_id=get_Data_CommentSubmission_Reddit, execution_date=20240422T090912, start_date=20240422T090916, end_date=20240422T090918
[2024-04-22T09:09:18.517+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task get_Data_CommentSubmission_Reddit (No data returned for comment t1_dataengineering; 18116)
[2024-04-22T09:09:18.560+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T09:09:18.611+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
